---
# tasks file for /ansible/ansible_poc/roles/logstash
  - name: This will install the required package for logstash "{{ item.key}}"
    package:
      name: "{{ item.value.url }}"
      state: "{{ item.value.ensure }}"
    with_dict: "{{ linux_packages }}"
    when: ansible_os_family  == "RedHat"
