---
# Setting up nginx
  - name: Updating centos.repo file
    copy:
      src: /app/ansible_poc/roles/nginx/files/centos.repo
      dest: /etc/yum.repos.d/centos.repo

  - name: Installing EPEL repo
    yum:
      name: epel-release
      update_cache: yes
      state: latest
    when: ansible_hostname == "nodemanager"

  - name: Installing patch utility on machines
    yum:
      name: patch
      update_cache: yes
      state: latest
    when: ansible_hostname == "nodemanager"

  - name: Creates a directory to place nginx html files
    file:
      path: /app/nginx/html
      recurse: yes
      state: directory
      
  - name: Changing Default configuration of nginx
    copy:
      src: /app/ansible_poc/roles/nginx/files/nginx_default.conf
      dest: /etc/nginx/nginx.conf


  - name: Setting up firewall to run nginx
    firewalld:
      service: http
      permanent: yes
      state: enabled
    notify: Firewalld services restarted
   
  - name: Setting up firewall to run nginx
    firewalld:
      port: 8080/tcp
      permanent: yes
      state: enabled
    notify: Firewalld services restarted

  - name: Creating welcome page for nginx service
    template:
      src: /app/ansible_poc/roles/nginx/templates/index.html.j2
      dest: /app/nginx/html/index.html
      mode: 0644

...

