---
# vars file for /app/ansible/roles/nginx

linux_directories:
  /app:
    owner: 'root'
    group: 'root'
    mode: 0755
  /app/nginx:
    owner: 'root'
    group: 'root'
    mode: 2755
  /app/nginx/html:
    owner: 'root'
    group: 'root'
    mode: 2755
  /app/nginx/modules:
    owner: 'root'
    group: 'root'
    mode: 2755
  /app/download:
    owner: 'root'
    group: 'root'
    mode: 0755
  /etc/nginx:
    owner: 'root'
    group: 'root'
    mode: 0755
  /etc/nginx/conf.d:
    owner: 'root'
    group: 'root'
    mode: 0755
  /etc/nginx/default.d:
    owner: 'root'
    group: 'root'
    mode: 0755
  /usr/share:
    owner: 'root'
    group: 'root'
    mode: 0755
  /usr/share/nginx:
    type: 'link'
    owner: 'root'
    group: 'root'
    target: '/app/nginx'
    mode: 0755

linux_packages:
  'java':
    ensure: latest
  'nginx':
    ensure: latest

nginx_config_owner: 'root'
nginx_config_group: 'root'
nginx_config_app_home: '/app/nginx'
nginx_config_app_modules: '/app/nginx/modules'
nginx_config_app_html: '/app/nginx/html'
nginx_config_nginx: '/etc/nginx/nginx.conf'
nginx_config_nginx_logs: '/app/nginx/logs'
