---
  - name: Copying configuration file
    copy:
      src: files/httpd.conf.file
      dest: /etc/httpd/conf/httpd.conf

  - name: Creating Homepage for apache
    copy:
      src: files/index.html.file
      dest: /var/www/html/index.html
    notify:
      - restart apache
