---
# vars file for /application/ansible_poc/roles/kafka
linux_directories:
  - /application/kafka/
  - /application/download/

application_ports:
  - 9092/tcp
  - 2181/tcp
application_configs:
  - application:
     - name: kafka
       template: kafka_service.j2
       service_name: kafka.service
     - name: zookeeper
     - template: zookeeper_service.j2
       service_name: zookeeper.service

kafka_owner: kafka
kafka_group: root
kafka_uid: 3001
kafka_gid: 0
kafka_package_url: http://mirrors.estointernet.in/apache/kafka/2.3.0/kafka_2.11-2.3.0.tgz
package_download_dir: /application/download/
kafka_home_dir: /application/kafka/
package_location: /application/download/kafka_2.11-2.3.0.tgz
service_dir: /etc/systemd/system/
